export const LOGIN = {
  CHECK_IN: 'LOGIN_CHECK_IN',
  CHECK_OUT: 'LOGIN_CHECK_OUT',
  SIGN_UP: 'SIGN_UP',
};

export const ALBUM = {
  SET_ALBUM: 'SET_ALBUM',
};

export const GAME = {
  SET_GAME: 'SET_GAME',
  RESET_GAME: 'RESET_GAME',
  DRAW_A_BALL: 'DRAW_A_BALL',
  SET_PIC_NUM: 'SET_PIC_NUM',
  SET_CARDS: 'SET_CARDS',
};

export const PLAYER = {
  SET_CARDS: 'SET_CARDS',
  SET_COLOR: 'SET_COLOR',
  SET_PLAYER: 'SET_PLAYER',
};

export const SOCKET = {
  SET_CONNECTION: 'SET_CONNECTION',
  ADD_MSG: 'ADD_MSG',
  ON_ERROR: 'ON_ERROR',
};
